### ISSUE TITLE
How to loop to merge pdf

### ISSUE THREAD

**Issue by olopost** [gotenberg/gotenberg-php#11]
Sorry for a newbies question,

I want to merge pdf with pdfengine merge I have a loop for that based on the number of document to get.

I think to use this function : 
```php 
use Gotenberg\Gotenberg;
use Gotenberg\Stream;

$request = Gotenberg::pdfEngines($apiUrl)
    ->merge(
        Stream::path('/path/to/my.pdf'),
        Stream::path('/path/to/my2.pdf')
    );
```

How can I loop to add Stream::path ?

Thanks for your feedback.

Best regards

**Comment by gulien** [comment]
Hello @olopost,

Sorry for the delay! You may simply create an array of `Stream` objects and then do `merge(...$pdfs);`.
