### ISSUE TITLE
How to handle large file conversion (4gb)

### ISSUE THREAD

**Issue by ssatz** [gotenberg/gotenberg-php#13]
Hello, 

Thanks for the wonderful library. How to handle large file conversion?
I can see you have already used stream but i still get internal 500 error. 

Any suggestions?

**Comment by gulien** [comment]
Hello,

I guess your trying to convert office documents? If so, alas, LibreOffice does struggle a lot with large files, and I do not have a solution at the moment for such a scenario 👍

**Comment by ssatz** [comment]
@gulien Yes i am trying to convert excel to pdf.  Okay it seems to be a problem with LibreOffice itself
