### ISSUE TITLE
Disable Footer entirely rather than show the temporary filename?

### ISSUE THREAD

**Issue by NiklasBr** [gotenberg/gotenberg-php#17]
If there is an empty footer or header I would expect it to be empty. What is happening here?

To resolve issues like https://github.com/puppeteer/puppeteer/issues/2089 we need to generate separate PDF:s and then merge. Some pages should not have footer or header, while others should.

```php
        $this->gotenbergChromium = Gotenberg::chromium($this->baseUri)
            // No margins, but many pages will define using @page css rules
            ->margins(0, 0, 0, 0)
            // A4 in inches
            ->paperSize(8.275, 11.7)
            ->preferCssPageSize()
            ->printBackground();
```

Then later:

```php
        foreach ($documents as $document) {
            if ($document->showFooter()) {
                $this->gotenbergChromium->footer(
                    Stream::string('footer.html', $document->renderFooterHtml())
                );
            } else {
                $this->gotenbergChromium->footer(
                    Stream::string('footer.html', '')
                );
            }

            // Add main content
            // Save PDF content
            // Merge multiple pages
        }
```

Result:
![image](https://user-images.githubusercontent.com/279826/206511822-b387c501-048a-455a-8d0d-b37ff5b6a8a9.png)

**Comment by gulien** [comment]
Hello,

Your issue is actually the fact you're sending an empty footer. Try this instead 😄 

```php
foreach ($documents as $document) {
            if ($document->showFooter()) {
                $this->gotenbergChromium->footer(
                    Stream::string('footer.html', $document->renderFooterHtml())
                );
            }

            // Add main content
            // Save PDF content
            // Merge multiple pages
        }
```

**Comment by NiklasBr** [comment]
But I want *none* footer. See my PR for a solution.

**Comment by gulien** [comment]
I don’t get it 🤔 if you send none, you’ll have none.
And you don’t really need a « clearing » method, just a new request without the footer form field.

**Comment by NiklasBr** [comment]
Because Gotenberg and Chromium does not support multiple different `@page` CSS rules, we *must* generate multiple different PDF:s with different layouts, and then merge them together. Which is why we have to send new a new request for each `$document` in the above (abbreviated) code, without a way to reset the header and footer like provided in the PR the PDF will show the default Chromium footer, which is ugly.

**Comment by gulien** [comment]
>  without a way to reset the header and footer like provided in the PR the PDF will show the default Chromium footer, which is ugly.

That's the part I don't get. Here are the [rules](https://github.com/gotenberg/gotenberg/blob/main/pkg/modules/chromium/chromium.go#L812) in Gotenberg:

1. If a header and/or a footer is sent, Gotenberg enables the header & footer feature, using the header and/or the footer provided by the user (if only one of them, it uses a default value, i.e., `<html><head></head><body></body></html>` - which displays nothing).
2. If no header nor footer, Gotenberg disables the header & footer feature.

So, in your case, if you send no footer, it should either:

1. Use the default footer value if you send a header.
2. Disable the header/footer altogether.

Maybe you're issue is that you're reusing the `Chromium` instance (i.e., `$this->gotenbergChromium`) instead of creating a new one per document.

**Comment by gulien** [comment]
If you still want to reuse the same `Chromium` instance, you can do the following:

```php

foreach ($documents as $document) {
  if ($document->showFooter()) {
      $this->gotenbergChromium->footer(
          Stream::string('footer.html', $document->renderFooterHtml())
      );
  } else {
      $this->gotenbergChromium->footer(
          Stream::string('footer.html', '<html><head></head><body></body></html>')
      );
  }

  // Add main content
  // Save PDF content
  // Merge multiple pages
}
```

**Comment by gulien** [comment]
But the best option would be something like:

```php
foreach ($documents as $document) {
  $builder = Gotenberg::chromium($this->baseUri)
                  // No margins, but many pages will define using @page css rules
                  ->margins(0, 0, 0, 0)
                  // A4 in inches
                  ->paperSize(8.275, 11.7)
                  ->preferCssPageSize()
                  ->printBackground();

  if ($document->showFooter()) {
      $builder->footer(
          Stream::string('footer.html', $document->renderFooterHtml())
      );
  }

 // ...
}
```
