### ISSUE TITLE
Wrong merge order if > 26 files

### ISSUE THREAD

**Issue by craigh** [gotenberg/gotenberg-php#21]
refs #9 

your Index class produces something like

`A B C D E F ... AA AB AC ...`

except when sorting, `AB` comes before `B`, so it is sorted wrongly.

I recommend deleting your Index class and using something like this (untested):

```php

    public function merge(Stream $pdf1, Stream $pdf2, Stream ...$pdfs): RequestInterface
    {
        foreach ([$pdf1, $pdf2, ...$pdfs] as $pdf) {
            $this->formFile(hrtime(true) . '_' . $pdf->getFilename(), $pdf->getStream());
        }

        $this->endpoint = '/forms/pdfengines/merge';

        return $this->request();
    }

```

**Comment by gulien** [comment]
Good catch!

**Comment by gulien** [comment]
Hello @craigh! Does the latest release works as expected for you?

**Comment by craigh** [comment]
@gulien yes, it works great! thank you!

**Comment by ytilotti** [comment]
Same error today. Hard to find, problem with `toAlpha` function on the modulo 26.
I will upgrade the lib.
