### ISSUE TITLE
How to convert a remote docx on s3 to PDF?

### ISSUE THREAD

**Issue by tanshiqi** [gotenberg/gotenberg-php#22]
I'm not sure but it failed:

```PHP
Gotenberg::libreOffice('http://localhost:3000')
        ->convert('Some remote file on s3.pdf');
```

**Comment by gulien** [comment]
Hello @tanshiqi,

Could you share the exception error message?

**Comment by tanshiqi** [comment]
Expected type 'Gotenberg\Stream'. Found 'string'.

**Comment by tanshiqi** [comment]
My mistake, I missed "Stream::path". It work now! thx

**Comment by gulien** [comment]
Cool 😄 👍
