### ISSUE TITLE
Upload Merged File to S3

### ISSUE THREAD

**Issue by iamnitinviras** [gotenberg/gotenberg-php#23]
How can we upload merged file to S3 without storing it to local storage.
Here is my code.

`$array=[Stream::path($file_name),Stream::path($file_name),Stream::path($file_name)];

$request = Gotenberg::libreOffice("https://demo.gotenberg.dev")
->outputFilename('merged')
->merge()
->convert(...$array)`

**Comment by gulien** [comment]
Hello @iamnitinviras,

With the [webhook](https://gotenberg.dev/docs/modules/webhook) feature, you may upload directly to S3. I do not have a detailed tutorial on how to do that exactly, but I know that several users have been using this features to do so.
