### ISSUE TITLE
Request times out, while testing locally

### ISSUE THREAD

**Issue by delcin-raj** [gotenberg/gotenberg-php#37]
My Php code
`$request = Gotenberg::chromium('http://127.0.0.1:3000')
        ->url("http://host.docker.internal:8000/invoice/view");`
`$response = Gotenberg::send($request);`
  OS is ubuntu 22.
  Docker container was started using `docker run --rm --add-host host.docker.internal:host-gateway -p 3000:3000 gotenberg/gotenberg:7`
 
 Was able to successfully curl from within the docker instance by following the commands
 `
 docker exec -it <hash> bash;
 curl "http://host.docker.internal:8001/invoice/view"
 `
 
 Docker logs 
 "
  {"level":"error","ts":1704128572.4625182,"logger":"api","msg":"convert URL to PDF: convert to PDF: context deadline exceeded","trace":"ba64d68d-0eb2-4834-831a-8db4d8415904","remote_ip":"172.17.0.1","host":"127.0.0.1:3000","uri":"/forms/chromium/convert/url","method":"POST","path":"/forms/chromium/convert/url","referer":"","user_agent":"GuzzleHttp/7","status":503,"latency":30001594641,"latency_human":"30.001594641s","bytes_in":203,"bytes_out":19}
 "

**Comment by gulien** [comment]
Hello @delcin-raj,

Try increasing the API timeout.

**Comment by delcin-raj** [comment]
I tried with 180s, but that still resulted in time out.
What is the expected time to convert a single page table with 2 images to a
pdf, when we test locally?

My laptop specs are Reyzen 7 4000, with 16gb RAM.

**Comment by gulien** [comment]
Are those images accessible within the Gotenberg instance?

**Comment by delcin-raj** [comment]
Was able to curl and download the image successfully,
have attached the screenshot of the curl command and the success status.
![image](https://github.com/gotenberg/gotenberg-php/assets/42584001/99511dbe-9580-4c59-97b0-bebcfdb1809a)

**Comment by gulien** [comment]
Can you attach the debug logs of your Gotenberg instance?

**Comment by shinanmhd** [comment]
hi @delcin-raj , i'm faced with the same problem, could you let me know how you fixed it

**Comment by wazimshizm** [comment]
I have the exact same issue. @delcin-raj did you solve?

**Comment by spointecker** [comment]
I am having the same issue, here the container logs:
```
A Docker-powered stateless API for PDF files.
Version: 7.0.1
-------------------------------------------------------
[SYSTEM] modules: api chromium gc libreoffice logging pdfcpu pdfengines pdftk unoconv unoconv-pdfengine 
[SYSTEM] gc: application started
[SYSTEM] api: server listening on port 3000
{"level":"error","ts":1732788901.9013093,"logger":"api","msg":"handle request: convert HTML to PDF: convert to PDF: chromium PDF: context deadline exceeded","trace":"6900d1df-5fbd-49d9-8702-747874f1640b","remote_ip":"10.42.0.71","host":"iampdf:3000","uri":"/forms/chromium/convert/html","method":"POST","path":"/forms/chromium/convert/html","referer":"","user_agent":"Symfony HttpClient (Curl)","status":503,"latency":30021908634,"latency_human":"30.021908634s","bytes_in":26702,"bytes_out":19}
```

**Comment by wazimshizm** [comment]
> I am having the same issue, here the container logs:
> 
> ```
> A Docker-powered stateless API for PDF files.
> Version: 7.0.1
> -------------------------------------------------------
> [SYSTEM] modules: api chromium gc libreoffice logging pdfcpu pdfengines pdftk unoconv unoconv-pdfengine 
> [SYSTEM] gc: application started
> [SYSTEM] api: server listening on port 3000
> {"level":"error","ts":1732788901.9013093,"logger":"api","msg":"handle request: convert HTML to PDF: convert to PDF: chromium PDF: context deadline exceeded","trace":"6900d1df-5fbd-49d9-8702-747874f1640b","remote_ip":"10.42.0.71","host":"iampdf:3000","uri":"/forms/chromium/convert/html","method":"POST","path":"/forms/chromium/convert/html","referer":"","user_agent":"Symfony HttpClient (Curl)","status":503,"latency":30021908634,"latency_human":"30.021908634s","bytes_in":26702,"bytes_out":19}
> ```

My issue was using Laravel, by default only one service worker is running. When you run gotenberg, you make a request using one worker, gotenberg then makes a request back to your application, which requires a second worker to answer. This was causing it to timeout for me because the first worker is busy with my initial request and can't answer gotenberg. If you're using Laravel set PHP_CLI_SERVER_WORKERS=2 atleast.

**Comment by spointecker** [comment]
I upgraded to the latest v7 version (7.10.2) and now it is working for me, but don't know why.
