### ISSUE TITLE
Content of ->html(Stream::string('index.html', $html)) is not added to PDF when header and/or footer are added to each page of the PDF

### ISSUE THREAD

**Issue by schmidt-travixmedia** [gotenberg/gotenberg-php#38]
If I add a header and/or footer to each page of the PDF, the main content between header and footer is missing
when using the string() method of Stream class:
`->html(Stream::string('index.html', $html));`

If I use the path() method of the Stream class instead, it works:
`->html(Stream::path('/var/www/html/public/test.html'));`

When I comment out header() and footer() chained methods, 
`->html(Stream::string('index.html', $html));`
is also working.

Is this a bug or am I missing something?

This is my test script:
```
<?php

use Gotenberg\Gotenberg;
use Gotenberg\Stream;

require_once "vendor/autoload.php";

//$html = file_get_contents('/var/www/html/public/test.html');

$chromium = Gotenberg::chromium('http://gotenberg:3000')
    //->pdf() // uncomment for gotenberg/gotenberg-php ^2.0; Same results on version 2.0.0
    ->header(Stream::path('http://nginx:80/header/de'))
    ->footer(Stream::path('http://nginx:80/footer/de'))


    // With this, main content will not be printed to PDF if header() and/or footer() are also chained;
    // If header() and footer() are commented out, main content is printed correctly to PDF
    //->html(Stream::string('index.html', $html));


    // with this, main content is ALWAYS printed correctly to PDF
    ->html(Stream::path('/var/www/html/public/test.html'));

$response = Gotenberg::send($chromium);
file_put_contents('/var/www/html/public/test.pdf', $response->getBody()->getContents());

echo "done.\n";
```

**Comment by gulien** [comment]
Hello @schmidt-travixmedia,

I do not see any reason in the package code for this behavior 🤔 

A few questions / remarks:

1. Is `Stream::path('http://nginx:80/header/de')` actually working? Never thought of this usage with `Stream::path`!
2. Is the content from `Stream::path('/var/www/html/public/test.html')` and `Stream::string('index.html', $html)` the same?
3. Could you give me the actual form data send to Gotenberg in all scenarios? Either from Gotenberg debug logs and/or by printing the Guzzle requests?

**Comment by schmidt-travixmedia** [comment]
Hello Gulien,

thanks for your response.

1. Yes, it works: URLs can be used (that's good!). In the example, the header/footer is delivered from a Docker container resource. Idea for an enhancement to make things more clear: create a new function url() in the Stream class. This would offer an "official" solution for embedding dynamic header/footer (instead of the workaround "temporarily store header/footer to files first, then load the files by Stream::path() function")
2. Yes, 100% the same HTML content.
3. I'll try to deliver the data you requested in a later comment here.

**Comment by gulien** [comment]
@schmidt-travixmedia are you able to reproduce this issue?
