### ISSUE TITLE
not working php:8.3.4

### ISSUE THREAD

**Issue by xiaoshangmin** [gotenberg/gotenberg-php#40]
php:8.3.4
gotenberg：8.3.0
Executing the following code always returns：code=405, message=Method Not Allowed
`  
$request = Gotenberg::libreOffice("http://gotenberg:3000")
            ->convert(Stream::path(BASE_PATH . '/storage/pdf/2023.docx'));
        Gotenberg::save($request, BASE_PATH . '/storage');
`

Docker logs
{"level":"error","ts":1712074302.3096998,"logger":"api","msg":"code=405, message=Method Not Allowed","trace":"86ea7b13-eeb4-4cb6-b208-b6eca9267db6","remote_ip":"172.19.0.3","host":"gotenberg:3000","uri":"/forms/libreoffice/convert","method":"PUT","path":"/forms/libreoffice/convert","referer":"","user_agent":"GuzzleHttp/7","status":405,"latency":58400,"latency_human":"58.4µs","bytes_in":0,"bytes_out":18}

**Comment by gulien** [comment]
Please reopen if you find anything 😄
