### ISSUE TITLE
Laravel 10 : need help

### ISSUE THREAD

**Issue by aeq-dev** [gotenberg/gotenberg-php#43]
Hi,
I'm trying to print blade view using url, Stream 
Url : 
```
 $request = Gotenberg::chromium('http://gotenberg:3000')
                        ->pdf()
                        ->skipNetworkIdleEvent()
                        ->url(url('template4'));
```
I get a blank pdf page, while if I use other url like google.com, it works fine.
NB: I can access to `url('template4')`.

Stream : 
```
$inv = view('print.sales.templates.4.main')->render();

                    $request = Gotenberg::chromium('http://gotenberg:3000')
                        ->pdf()
                        ->html(Stream::string('my.html', $inv));
```
It works but without CSS !! (I'm using boostrap css)

What am I missing ?

**Comment by gulien** [comment]
Closing in favor of https://github.com/gotenberg/gotenberg/discussions/889.
