### ISSUE TITLE
Addition of a render endpoint

### ISSUE THREAD

**Issue by mariusjp** [gotenberg/gotenberg-php#44]
What I need is an endpoint that does the same as the "merge" endpoint (not do any converting / "touching" the raw data) and just accept the stream and create a PDF, but then, for a single PDF.

What I have done atm is "hack" the php-client and added a "render" method which removes the second and third argument (Stream $pdf2, Stream ...$pdfs) and just set the data for a single PDF and send it to the "merge" endpoint, and this works perfectly. But this feels very incorrect.

I'm just not fluent enough in Go to open a PR and help you guys with the Go side of things.
I wouldn't mind opening a PR to the php-client side though and maybe even make it more extensible (atm I had to copy the entire class because of concrete types and private properties in stead of interfaces and protected properties (e.g.)).

**Comment by gulien** [comment]
I'm still struggling to understand your use case 😄 but maybe that's me having a brain fart I don't know lol

**Comment by mariusjp** [comment]
Maybe this bit of code will help understand the use case:

```php
final class RequestGenerator
{
    /**
     * @param array<int, string>|Collection<int, string> $labels
     */
    public static function create(array|Collection $labels): RequestInterface
    {
        if (\is_array($labels)) {
            $labels = collect($labels);
        }

        if ($labels->count() >= 2) {
            $request = Gotenberg::pdfEngines(\strval(config('services.gotenberg.url')))
                ->merge(
                    ...\array_map(
                        function (string $label): Stream {
                            return Stream::string(
                                'index.pdf',
                                $label,
                            );
                        },
                        $labels->all(),
                    ),
                );
        } else {
            $request = Gotenberg::pdfEngines(\strval(config('services.gotenberg.url')))
                ->render(
                    Stream::string(
                        'index.pdf',
                        $labels->all()[0],
                    ),
                );
        }

        return $request;
    }
}
```

Here you'll also see my "render" implementation by extending the PDFEngines class and adding a method that calls the "merge" endpoint with a single PDF.

And here you'll see the flow where every type of PDF is first handled by it's unique case and then eventually merged as one big PDF.

```php
$requestStreams = [];
if ($glsShipments->count() > 0) {
    $requestStreams[] = $this->createGLSLabel->multiple($glsShipments);
}
if ($sendCloudShipments->count() > 0) {
    $requestStreams[] = $this->createSendCloudLabel->multiple($sendCloudShipments);
}
if ($otherShipments->count() > 0) {
    $requestStreams[] = $this->createOtherLabel->multiple($otherShipments);
}

if (\count($requestStreams) === 0) {
    throw new \RuntimeException('No shipments to print.');
}

// This is the "mother of all merges" and combines all PDFs
$request = RequestGenerator::create($requestStreams);

$response = Gotenberg::send($request);
```

**Comment by gulien** [comment]
```php
// This is the "mother of all merges" and combines all PDFs
if (\count($requestStreams) >= 2) {
  $request = RequestGenerator::create($requestStreams);
  $response = Gotenberg::send($request);
}

// Create a custom response with your unique PDF?
```

**Comment by mariusjp** [comment]
> ```
> // This is the "mother of all merges" and combines all PDFs
> if (\count($requestStreams) >= 2) {
>   $request = RequestGenerator::create($requestStreams);
>   $response = Gotenberg::send($request);
> }
> 
> // Create a custom response with your unique PDF?
> ```

But then I would need a separate library / logic to merge the Gotenberg PDF data and the base64encoded data.
Or I would need to start saving them as files and then call the merge endpoint.
All extra steps to  avoid the "merge" endpoint that *demands* 2 inputs and variadic, when it can just accept variadic and I can "cheese" my logic into it 😅

**Comment by gulien** [comment]
Haha ok yes I got it. Still, the idea behind this is to avoid unnecessary calls to Gotenberg. I'm not convince it should be part of this library 🤔

**Comment by mariusjp** [comment]
Fair point! I do believe that my initial request for a "render" endpoint does feel kinda weird, because that's not the purpose of Gotenberg.
*But*, the merge endpoint __basically__ does a "render" of sorts, it doesn't intervene with the creation of the PDF the same way a render endpoint would.
That's why I'm using it to render a single PDF within the flow.

But, that's my view, this is not my project, not my place to decide!

It would be nice if you could consider removing the strict demand of 2 PDF streams and just using the variadic (just like `\array_merge` for example)

**Comment by gulien** [comment]
@mariusjp feel free to open a PR!

**Comment by mariusjp** [comment]
I guess this isn't closed yet because of not having released it yet, which comes in handy because I have a problem.

I forked with the checkbox (didn't notice it the first time) "Only fork main branch"

Now I don't have the tags to also implement this for 1.1.8, because that's where I actually need this fix 😅

Any tips on how to open a PR now for that specific tag?

**Comment by gulien** [comment]
Oh! I don't support previous major release, sorry. Consider upgrading if possible 😬

**Comment by mariusjp** [comment]
> Oh! I don't support previous major release, sorry. Consider upgrading if possible 😬

No problem! We were considering upgrading anyway!
