### ISSUE TITLE
Can't set FILENAME 

### ISSUE THREAD

**Issue by davidreyg** [gotenberg/gotenberg-php#46]
![image](https://github.com/user-attachments/assets/d090a114-b4b2-4b50-848a-ab2522cb1903)

after setting outputFileName(). returns MultipartFormDataModule NOT a Chromium instance
![image](https://github.com/user-attachments/assets/d6a9445f-b99e-461e-83f9-aad6a67b0dda)

**Comment by gulien** [comment]
Hello @davidreyg,

I have the feeling that your IDE is misleading you somehow 🤔 does it actually run?

**Comment by davidreyg** [comment]
Actually yes. I managed to display in a new page the content

![image](https://github.com/user-attachments/assets/f281edc3-0063-4f41-bc64-eee72ed706d8)

But maybe i'm missing something.

**From the docs**

Filename
You may override the output filename with:

use Gotenberg\Gotenberg;

```php
$request = Gotenberg::chromium('http://localhost:3000')
    ->pdf()
    ->outputFilename('my_file')
    ->url('https://my.url');
```

Gotenberg will automatically add the correct file extension.

But, as you saw, when I set the outputFilename() I can't  use Chromium class methods

**Comment by gulien** [comment]
But does your code actually work at runtime with the method `outputFilename`? I try to understand if it’s just your IDE misinterpreting `trait` or me that’s missed something as obvious lol (and you’re the first finding it after many years 😅)

**Comment by davidreyg** [comment]
Mmm actually, when using the metod `outputFilename` is not working. I'm using VS Code inside an ubuntu server. 
I don't think is [ide_helper](https://github.com/barryvdh/laravel-ide-helper) problem. 
But anyway i don't know if that's  a bug. :(

**Comment by gulien** [comment]
@davidreyg I've just tested it and it works fine:

<img width="454" alt="Capture d’écran 2024-07-29 à 10 14 31" src="https://github.com/user-attachments/assets/4f4163f9-ff01-4693-82e1-3e8c2d076c74">

I think you have a bug in your IDE or something else is wrong on your end. But as far as this library is concerned, there is no bug 👍
