### ISSUE TITLE
Basic Authentication

### ISSUE THREAD

**Issue by mforstme** [gotenberg/gotenberg-php#47]
Hello,

I would like to know how I can enter my username and password if Basic Authentication is enabled. 

I couldn't find anything in the code that handles this, so I assume it still needs to be implemented. 

Could you please provide guidance or confirm if this feature is planned?

Thank you!

**Comment by gulien** [comment]
Hello @mforstme 👋 

This library generates "standard" _RequestInterface_, so you are able to do this:

```php
use Gotenberg\Gotenberg;
use function base64_encode;

$username = 'foo';
$password = 'bar';

$req = Gotenberg::chromium('http://localhost:3000')
    ->pdf()
    ->outputFilename('foo')
    ->landscape()
    ->url('https://google.com')
    ->withHeader('Authorization', 'Basic ' . base64_encode($username . ':' . $password));
```
