### ISSUE TITLE
Images and fonts not displaying from HTML

### ISSUE THREAD

**Issue by tristanvann** [gotenberg/gotenberg-php#52]
Using this code:

```
<?php

use Gotenberg\Gotenberg;
use Gotenberg\Stream;

require_once 'vendor/autoload.php';

$html = file_get_contents('../pdf/template.html');

$apiUrl = 'http://localhost:3000/';

$request = Gotenberg::chromium($apiUrl)
	->pdf()
	->outputFilename('test')
	->html(Stream::string('index.html', $html));

$filename = Gotenberg::save($request, '../pdf/saved/');

?>
```

The HTML has an img in it, as well as custom fonts, but the final PDF does not show the image nor fonts. What am I missing here?

**Comment by gulien** [comment]
You may have to send the assets (images, fonts) alongside your HTML content. See https://gotenberg.dev/docs/routes#html-file-into-pdf-route.

**Comment by tristanvann** [comment]
There is no documentation for how to do that in PHP, only cURL. Some instruction on proper methods or syntax would be nice. Right now I'm not even sure how to find that besides comb through the source code or just guess.

**Comment by gulien** [comment]
Indeed, in this case its not clear. What you're looking for is:

https://github.com/gotenberg/gotenberg-php/blob/e8bc519812349f7bd57b294b4ea41dce53693b7c/src/Modules/ChromiumMultipartFormDataModule.php#L166

For other form fields, it should be quite obvious as the methods share the same name.
